# Generated by Django 2.2 on 2019-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_belt_app', '0003_auto_20191213_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
