# Generated by Django 2.2 on 2019-12-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_belt_app', '0004_wish_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dojo_belt_app.User')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dojo_belt_app.Wish')),
            ],
        ),
    ]
